# Build angular client
FROM node:14 as client

WORKDIR /build

COPY client/package.json .
RUN npm install

COPY client/ .
RUN npm run build

# Build runtime image
FROM nginx

# Copy the built angular files
COPY --from=client /build/dist/ /usr/share/nginx/html
