# B"H
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

name: Create Release

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # - name: Get tag name
      #   id: tag_name 
      #   run: echo "::set-output name=SOURCE_TAG::${env.GITHUB_REF#refs/tags/}"
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          # registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y%m%d-%H-%M-%S')"

      - name: Get Tag Name
        id: push_path
        run: |
          echo "$(echo $GITHUB_REF | cut -d / -f 3)"
          echo "::set-output name=tag_name::$(echo $GITHUB_REF | cut -d / -f 3)"
          echo "::set-output name=repo_name::$(echo $IMAGE_NAME | cut -d / -f 2)"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKERHUB_USER }}/${{ steps.push_path.outputs.repo_name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ steps.push_path.outputs.tag_name }}
            type=raw,value=${{ steps.push_path.outputs.tag_name }}-{{ sha }}
            type=raw, value=${{ steps.push_path.outputs.tag_name }}-${{ steps.date.outputs.date }}


      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    outputs:
      tags: "${{ steps.push_path.outputs.tag_name }}-${{ steps.date.outputs.date }}, ${{ steps.push_path.outputs.tag_name }}"


  release:
    needs: [build-and-push-image]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - ${{ github.event.head_commit.message }}
            - Dockerhub tags: 
              ${{ needs.build-and-push-image.outputs.tags }}
              docker pull ${{ secrets.DOCKERHUB_USER }}/{{ tag }}
          draft: false
          prerelease: false